const constants = {
    ADD_CONTACT: "ADD_CONTACT",
    REMOVE_CONTACT: "REMOVE_CONTACT",
    SELECT_CONTACT: "SELECT_CONTACT",
    UPDATE_CONTACT: "UPDATE_CONTACT",
    SEARCH_CONTACT: "SEARCH_CONTACT",
    GET_INITIAL_CONTACTS: "GET_INITIAL_CONTACTS"
};

export default constants;
